---
- hosts: loadbalancer
  become: true
  tasks:
    - name: Install HAProxy
      apt:
        name: haproxy
        state: present
        update_cache: true

    - name: Copy HAProxy config
      template:
        src: templates/haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
      notify:
        - Restart HAProxy

  handlers:
    - name: Restart HAProxy
      service:
        name: haproxy
        state: restarted
